version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 3711521
      MYSQL_DATABASE: imersao17
      MYSQL_PASSWORD: 3711521
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql
